# coding: utf-8
APP_USERS_GENDER_MAN = 'm'
APP_USERS_GENDER_WOMAN = 'f'
APP_USERS_GENDER_UNDEF = 'n'

APP_USERSRELS_RELS_TYPE_UNDEF = 0
APP_USERSRELS_RELS_TYPE_FRIEND = 9
APP_USERSRELS_RELS_TYPE_SEND_TO = 1
APP_USERSRELS_RELS_TYPE_FROM_USER = 2
