"""Init migrations

Revision ID: 531f9b3340b7
Revises: 
Create Date: 2014-12-10 17:14:14.275213

"""

# revision identifiers, used by Alembic.
revision = '531f9b3340b7'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('content_search_name_gin_idx', 'content', ['search_name'], unique=False, postgresql_using='gin')
    op.create_index('mediaunits_search_name_gin_idx', 'media_units', ['search_name'], unique=False, postgresql_using='gin')
    op.drop_index('mediaunits_search_description_gin_idx', table_name='media_units')
    op.create_index('person_search_name_gin_idx', 'persons', ['search_name'], unique=False, postgresql_using='gin')
    op.drop_index('persons_search_name_gin_idx', table_name='persons')
    op.create_index('topic_search_description_gin_idx', 'topics', ['search_description'], unique=False, postgresql_using='gin')
    op.create_index('topic_search_name_gin_idx', 'topics', ['search_name'], unique=False, postgresql_using='gin')
    op.drop_index('topics_search_description_gin_idx', table_name='topics')
    op.drop_index('topics_search_name_gin_idx', table_name='topics')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('topics_search_name_gin_idx', 'topics', ['search_name'], unique=False)
    op.create_index('topics_search_description_gin_idx', 'topics', ['search_description'], unique=False)
    op.drop_index('topic_search_name_gin_idx', table_name='topics')
    op.drop_index('topic_search_description_gin_idx', table_name='topics')
    op.create_index('persons_search_name_gin_idx', 'persons', ['search_name'], unique=False)
    op.drop_index('person_search_name_gin_idx', table_name='persons')
    op.create_index('mediaunits_search_description_gin_idx', 'media_units', ['search_name'], unique=False)
    op.drop_index('mediaunits_search_name_gin_idx', table_name='media_units')
    op.drop_index('content_search_name_gin_idx', table_name='content')
    ### end Alembic commands ###
