# coding: utf-8
APP_MEDIA_TYPE_AUDIO = u'a'
APP_MEDIA_TYPE_VIDEO = u'v'
APP_MEDIA_TYPE_PICTURE = u'p'
APP_MEDIA_TYPE_DEFAULT = u'd'

APP_MEDIA_TYPE = (
    (APP_MEDIA_TYPE_AUDIO, u'Аудио'),
    (APP_MEDIA_TYPE_VIDEO, u'Видео'),
    (APP_MEDIA_TYPE_PICTURE, u'Картинка'),
)

APP_MEDIA_TYPE_WITH_DEFAULT = APP_MEDIA_TYPE + (
    (APP_MEDIA_TYPE_DEFAULT, u'По умолчанию'),
)

APP_MEDIA_ACCESS_LIST = u't'
APP_MEDIA_BLACK_LIST = u'f'
APP_MEDIA_LIST = (
    (APP_MEDIA_ACCESS_LIST, u'Допустимый список'),
    (APP_MEDIA_BLACK_LIST, u'Недопустимый список')
)

APP_ACCESS_LEVEL_OWNER_MASK = int('011000000000', 2)
APP_ACCESS_LEVEL_MANAGER_MASK = APP_ACCESS_LEVEL_OWNER_MASK >> 3
APP_ACCESS_LEVEL_AUTH_USER_MASK = APP_ACCESS_LEVEL_MANAGER_MASK >> 3
APP_ACCESS_LEVEL_GUEST_MASK = APP_ACCESS_LEVEL_AUTH_USER_MASK >> 3

APP_ACCESS_LEVEL_DEFAULT = '111111110000'