# coding: utf-8
APP_MEDIA_TYPE_AUDIO = 'a'
APP_MEDIA_TYPE_VIDEO = 'v'
APP_MEDIA_TYPE_PICTURE = 'p'

APP_MEDIA_TYPE = (
    (APP_MEDIA_TYPE_AUDIO, u'Аудио'),
    (APP_MEDIA_TYPE_VIDEO, u'Видео'),
    (APP_MEDIA_TYPE_PICTURE, u'Картинка'),
)

APP_ACCESS_LEVEL_OWNER = 4
APP_ACCESS_LEVEL_MANAGER = 4
APP_ACCESS_LEVEL_AUTH_USER = 2
APP_ACCESS_LEVEL_GUEST = 0

APP_ACCESS_LEVEL = APP_ACCESS_LEVEL_OWNER * 1000 + APP_ACCESS_LEVEL_MANAGER * 100 + APP_ACCESS_LEVEL_AUTH_USER * 10 + APP_ACCESS_LEVEL_GUEST