# coding: utf-8
APP_MEDIA_TYPE_AUDIO = 'a'
APP_MEDIA_TYPE_VIDEO = 'v'
APP_MEDIA_TYPE_PICTURE = 'p'

APP_MEDIA_TYPE = (
    (APP_MEDIA_TYPE_AUDIO, u'Аудио'),
    (APP_MEDIA_TYPE_VIDEO, u'Видео'),
    (APP_MEDIA_TYPE_PICTURE, u'Картинка'),
)

APP_ACCESS_LEVEL_OWNER_MASK = int('011000000000', 2)
APP_ACCESS_LEVEL_MANAGER_MASK = APP_ACCESS_LEVEL_OWNER_MASK >> 3
APP_ACCESS_LEVEL_AUTH_USER_MASK = APP_ACCESS_LEVEL_MANAGER_MASK >> 3
APP_ACCESS_LEVEL_GUEST_MASK = APP_ACCESS_LEVEL_AUTH_USER_MASK >> 3

APP_ACCESS_LEVEL_DEFAULT = '111111110000'