# coding: utf-8
APP_PERSONS_STATUS_TYPE_NOT_ACTIVE = u'0'
APP_PERSONS_STATUS_TYPE_ACTIVE = u'1'

APP_PERSONS_STATUS_TYPE = (
    (APP_PERSONS_STATUS_TYPE_NOT_ACTIVE, u'Не активен'),
    (APP_PERSONS_STATUS_TYPE_ACTIVE, u'Активен'),
)