# coding: utf-8

# STATUS CODE
HTTP_OK = 200

HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_INTERNAL_SERVER_ERROR = 500


#VK SOCIAL AUTH
VK_CLIENT_ID = 4643948
VK_SECRET_KEY = 'qa9kXSjeRTMybQCh6J2I'
VK_REDIRECT_URI = 'http://serialov.tv/login/complete/vk-oauth2'

